In [1]:
import pandas as pd
from pandas import DataFrame

In [4]:
df = pd.read_excel('./8.27_상권_데이터_수정본.xlsx')
df = pd.DataFrame(df)

In [5]:
df

,상권_구분_코드_명,시군구명,총_매출_금액,점포수,개업_율,폐업_률,폐업_점포_수,프랜차이즈_점포_수,주중_매출_금액,주말_매출_금액,...,연령대_60_이상_생활인구_수,주중_생활인구_수,주말_생활인구_수,총_직장_인구_수,연령대_10_직장_인구_수,연령대_20_직장_인구_수,연령대_30_직장_인구_수,연령대_40_직장_인구_수,연령대_50_직장_인구_수,연령대_60_이상_직장_인구_수
0,계동길,종로구,2.306165e+09,95.0,4.00,3.0,0.75,4.0,1.586855e+09,719309412.0,...,60355.00,239118.50,72801.75,842.0,0.0,97.0,160.0,190.0,191.0,204.0
1,난계로27길,종로구,6.557127e+08,20.0,0.00,0.0,0.00,1.0,5.175920e+08,138120660.0,...,87981.75,258341.50,101390.75,201.0,1.0,18.0,42.0,61.0,40.0,39.0
2,돈화문로11가길,종로구,1.155523e+09,73.0,4.25,1.5,0.25,1.0,1.030174e+09,125348348.0,...,35306.75,131745.00,41271.75,3686.0,5.0,474.0,1086.0,1164.0,697.0,260.0
3,명륜길,종로구,5.653390e+07,24.0,0.00,0.0,0.00,1.0,5.055730e+07,5976601.0,...,122363.50,464815.25,184258.00,56.0,0.0,5.0,13.0,16.0,18.0,4.0
4,백석동길,종로구,1.580058e+09,22.0,4.25,5.0,0.25,0.0,8.785505e+08,701507168.0,...,48160.75,121695.50,52344.00,1797.0,0.0,355.0,581.0,496.0,273.0,92.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1539,창동상계_경제기반형,NaN,NaN,NaN,4.00,1.0,1.00,38.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1540,세운상가_중심시가지형,NaN,NaN,NaN,6.00,4.0,3.00,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1541,창덕궁앞_중심시가지형,NaN,NaN,NaN,8.00,1.0,1.00,10.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1542,신촌_일반근린형,NaN,NaN,NaN,3.00,3.0,5.00,60.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1543,창신숭인_일반근린형,NaN,NaN,NaN,12.00,6.0,2.00,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.shape

(1544, 45)

In [6]:
# 데이터 drop할거라서 복사해놓음
s1df = df.copy()

In [8]:
# 결측치 제거
s1df.isnull().sum()

상권_구분_코드_명             0
시군구명                  48
총_매출_금액              357
점포수                  357
개업_율                  56
폐업_률                  56
폐업_점포_수               56
프랜차이즈_점포_수            56
주중_매출_금액             357
주말_매출_금액             357
시간대_06~11_매출_금액      357
시간대_11~14_매출_금액      357
시간대_14~17_매출_금액      357
시간대_17~21_매출_금액      357
연령대_10_매출_금액         357
연령대_20_매출_금액         357
연령대_30_매출_금액         357
연령대_40_매출_금액         357
연령대_50_매출_금액         357
연령대_60_이상_매출_금액      357
아파트_단지_수             235
아파트_평균_면적            235
아파트_평균_시가            235
상권_변화_지표              48
상권_변화_지표_명            48
운영_영업_개월_평균           48
폐업_영업_개월_평균           48
총 상주인구 수              62
총 가구 수                62
총_생활인구_수              62
연령대_10_생활인구_수         62
연령대_20_생활인구_수         62
연령대_30_생활인구_수         62
연령대_40_생활인구_수         62
연령대_50_생활인구_수         62
연령대_60_이상_생활인구_수      62
주중_생활인구_수             62
주말_생활인구_수             62
총_직장_인구_수             80
연령대_10_직장_인구_수        80
연령대_20_직장_인구_수        80
연령대_30_직장_인구_수        80
연령대_40_직장_인구_수        80
연령대_50_직장_인구_수        80
연령대_60_이상_직장_인구_수     80
dtype: int64

In [9]:
s1df = s1df.dropna()

In [10]:
s1df.shape

(1086, 45)

In [14]:
# 구별 상관관계 요소 상위 5개 구하기(매출 데이터 제외)
s1df_c = s1df.drop(['점포수', '폐업_점포_수', '프랜차이즈_점포_수', '주중_매출_금액',
                   '주말_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
                   '시간대_14~17_매출_금액', '시간대_17~21_매출_금액','연령대_10_매출_금액',
                   '연령대_20_매출_금액', '연령대_30_매출_금액', '연령대_40_매출_금액',
                   '연령대_50_매출_금액', '연령대_60_이상_매출_금액'], axis=1)
s1df_c.sample(5)

,상권_구분_코드_명,시군구명,총_매출_금액,개업_율,폐업_률,아파트_단지_수,아파트_평균_면적,아파트_평균_시가,상권_변화_지표,상권_변화_지표_명,...,연령대_60_이상_생활인구_수,주중_생활인구_수,주말_생활인구_수,총_직장_인구_수,연령대_10_직장_인구_수,연령대_20_직장_인구_수,연령대_30_직장_인구_수,연령대_40_직장_인구_수,연령대_50_직장_인구_수,연령대_60_이상_직장_인구_수
1086,서울 강남구 선릉역_2,강남구,2.322881e+10,4.00,3.50,49.0,38.0,200869407.0,LL,다이나믹,...,211406.25,1216483.25,279286.25,40183.0,100.0,7240.0,10457.0,10558.0,10272.0,1556.0
423,증산로17길,은평구,1.214530e+07,8.25,0.00,40.0,57.0,149900389.0,LH,상권확장,...,141557.25,349705.25,143442.50,161.0,0.0,8.0,24.0,52.0,51.0,26.0
56,백범로79길,용산구,1.144765e+09,2.25,2.50,104.0,59.0,242145926.0,HH,정체,...,235145.00,889915.00,353398.00,899.0,3.0,106.0,256.0,270.0,165.0,99.0
241,면목로33길,중랑구,2.627602e+08,4.25,10.00,21.0,47.0,147093552.0,HL,상권축소,...,386490.25,1056742.00,447020.75,86.0,1.0,6.0,19.0,14.0,23.0,23.0
180,망우로21길,동대문구,4.665563e+08,0.00,6.25,4.0,52.0,207921429.0,HH,정체,...,59304.00,209856.25,87488.50,96.0,0.0,13.0,9.0,18.0,27.0,29.0

In [13]:
s1df.shape

(1086, 45)

In [15]:
#s1df drop 후
s1df_c.shape

(1086, 30)

In [17]:
s1df_c.columns

Index(['상권_구분_코드_명', '시군구명', '총_매출_금액', '개업_율', '폐업_률', '아파트_단지_수',
       '아파트_평균_면적', '아파트_평균_시가', '상권_변화_지표', '상권_변화_지표_명', '운영_영업_개월_평균',
       '폐업_영업_개월_평균', '총 상주인구 수', '총 가구 수', '총_생활인구_수', '연령대_10_생활인구_수',
       '연령대_20_생활인구_수', '연령대_30_생활인구_수', '연령대_40_생활인구_수', '연령대_50_생활인구_수',
       '연령대_60_이상_생활인구_수', '주중_생활인구_수', '주말_생활인구_수', '총_직장_인구_수',
       '연령대_10_직장_인구_수', '연령대_20_직장_인구_수', '연령대_30_직장_인구_수', '연령대_40_직장_인구_수',
       '연령대_50_직장_인구_수', '연령대_60_이상_직장_인구_수'],
      dtype='object')

In [19]:
a = s1df_c['시군구명']

In [20]:
a

0       종로구
1       종로구
2       종로구
3       종로구
4       종로구
       ...
1489    강동구
1490    용산구
1492     중구
1493    종로구
1494    송파구
Name: 시군구명, Length: 1086, dtype: object

In [29]:
a.unique() # 길이 25

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구'], dtype=object)

In [46]:
corr = s1df_c[s1df_c['시군구명'] == a.unique()[2]].corr(method='pearson')
corr

,총_매출_금액,개업_율,폐업_률,아파트_단지_수,아파트_평균_면적,아파트_평균_시가,운영_영업_개월_평균,폐업_영업_개월_평균,총 상주인구 수,총 가구 수,...,연령대_60_이상_생활인구_수,주중_생활인구_수,주말_생활인구_수,총_직장_인구_수,연령대_10_직장_인구_수,연령대_20_직장_인구_수,연령대_30_직장_인구_수,연령대_40_직장_인구_수,연령대_50_직장_인구_수,연령대_60_이상_직장_인구_수
총_매출_금액,1.000000,-0.099792,-0.041134,0.029823,0.254122,0.148307,-0.011615,-0.002800,0.250209,0.377632,...,0.102410,0.229311,0.259599,0.438037,0.181303,0.205243,0.512194,0.462491,0.501894,0.563573
개업_율,-0.099792,1.000000,0.491820,0.216303,-0.104676,-0.234788,0.004908,0.104900,0.029076,-0.004131,...,0.075688,0.042612,0.061967,-0.058391,-0.062963,-0.036673,-0.026936,-0.053048,-0.138461,-0.100092
폐업_률,-0.041134,0.491820,1.000000,0.092275,-0.060583,-0.076883,-0.148233,-0.115418,-0.043860,-0.059546,...,0.024278,-0.000257,0.019655,-0.162221,-0.155930,-0.146461,-0.134443,-0.126328,-0.127476,-0.162288
아파트_단지_수,0.029823,0.216303,0.092275,1.000000,-0.108549,-0.263704,-0.062185,0.082009,0.790338,0.716334,...,0.692887,0.632799,0.675686,-0.057194,-0.040041,-0.028693,-0.066009,-0.084780,-0.066861,0.094978
아파트_평균_면적,0.254122,-0.104676,-0.060583,-0.108549,1.000000,0.584917,-0.159492,-0.176395,0.040326,0.078894,...,-0.200834,-0.131738,-0.082307,0.022801,0.019630,0.002971,0.009317,0.015777,0.101913,0.073485
아파트_평균_시가,0.148307,-0.234788,-0.076883,-0.263704,0.584917,1.000000,-0.139371,-0.140363,-0.028800,0.025451,...,-0.284909,-0.212428,-0.196205,0.058064,0.004789,-0.002885,0.071781,0.083784,0.117377,0.147824
운영_영업_개월_평균,-0.011615,0.004908,-0.148233,-0.062185,-0.159492,-0.139371,1.000000,0.491924,-0.190362,-0.228471,...,-0.099297,-0.132241,-0.130154,0.022742,-0.000486,-0.029493,0.030316,0.054718,0.079069,0.177186
폐업_영업_개월_평균,-0.002800,0.104900,-0.115418,0.082009,-0.176395,-0.140363,0.491924,1.000000,-0.003519,-0.029282,...,0.062750,0.027582,0.017179,0.117125,0.093821,0.093872,0.085364,0.085857,0.146341,0.230649
총 상주인구 수,0.250209,0.029076,-0.043860,0.790338,0.040326,-0.028800,-0.190362,-0.003519,1.000000,0.980340,...,0.790690,0.797874,0.822782,0.081191,0.100993,0.112059,0.047142,-0.005431,0.027565,0.247984
총 가구 수,0.377632,-0.004131,-0.059546,0.716334,0.078894,0.025451,-0.228471,-0.029282,0.980340,1.000000,...,0.744947,0.778923,0.802296,0.158034,0.150867,0.165332,0.129572,0.064725,0.092360,0.314965
총_생활인구_수,0.238830,0.048429,0.005614,0.647069,-0.117499,-0.208190,-0.131965,0.024585,0.807266,0.787814,...,0.962885,0.998936,0.993854,0.052812,0.032506,0.058568,0.061915,-0.004382,-0.023169,0.239519
연령대_10_생활인구_수,-0.038426,0.059169,-0.012871,0.657277,-0.165924,-0.333901,-0.068340,0.105111,0.711883,0.628164,...,0.917663,0.904826,0.884160,-0.122495,-0.083996,-0.071298,-0.133216,-0.148376,-0.140227,0.062321
연령대_20_생활인구_수,0.453924,0.043466,0.020748,0.494177,-0.031483,-0.135076,-0.126420,-0.030063,0.682660,0.719722,...,0.816202,0.915361,0.916756,0.124838,0.050585,0.081160,0.157379,0.082974,0.064717,0.306517
연령대_30_생활인구_수,0.358537,0.002763,0.014377,0.589310,-0.041826,-0.084050,-0.214660,-0.047695,0.805729,0.817919,...,0.881550,0.958972,0.958490,0.131559,0.063008,0.096932,0.162048,0.082022,0.045193,0.307705
연령대_40_생활인구_수,0.217942,0.022527,-0.009703,0.625649,-0.118318,-0.164813,-0.155031,0.009037,0.816315,0.796414,...,0.939864,0.989871,0.973943,0.098048,0.069035,0.098615,0.105905,0.034269,-0.003683,0.275841
연령대_50_생활인구_수,0.179106,0.081433,-0.022342,0.663865,-0.133888,-0.222550,-0.061607,0.076922,0.811023,0.776674,...,0.961351,0.982524,0.974914,0.077501,0.072307,0.097057,0.070453,0.000908,-0.016521,0.267295
연령대_60_이상_생활인구_수,0.102410,0.075688,0.024278,0.692887,-0.200834,-0.284909,-0.099297,0.062750,0.790690,0.744947,...,1.000000,0.958589,0.964816,-0.036228,0.003589,0.018742,-0.047404,-0.105548,-0.107798,0.126023
주중_생활인구_수,0.229311,0.042612,-0.000257,0.632799,-0.131738,-0.212428,-0.132241,0.027582,0.797874,0.778923,...,0.958589,1.000000,0.987690,0.063482,0.041598,0.068340,0.071523,0.005107,-0.019083,0.249459
주말_생활인구_수,0.259599,0.061967,0.019655,0.675686,-0.082307,-0.196205,-0.130154,0.017179,0.822782,0.802296,...,0.964816,0.987690,1.000000,0.026745,0.010403,0.034608,0.038319,-0.027117,-0.032772,0.213581
총_직장_인구_수,0.438037,-0.058391,-0.162221,-0.057194,0.022801,0.058064,0.022742,0.117125,0.081191,0.158034,...,-0.036228,0.063482,0.026745,1.000000,0.798676,0.841068,0.944094,0.847065,0.713371,0.749635
연령대_10_직장_인구_수,0.181303,-0.062963,-0.155930,-0.040041,0.019630,0.004789,-0.000486,0.093821,0.100993,0.150867,...,0.003589,0.041598,0.010403,0.798676,1.000000,0.991000,0.592855,0.370363,0.250989,0.438526
연령대_20_직장_인구_수,0.205243,-0.036673,-0.146461,-0.028693,0.002971,-0.002885,-0.029493,0.093872,0.112059,0.165332,...,0.018742,0.068340,0.034608,0.841068,0.991000,1.000000,0.650027,0.432638,0.301376,0.473584
연령대_30_직장_인구_수,0.512194,-0.026936,-0.134443,-0.066009,0.009317,0.071781,0.030316,0.085364,0.047142,0.129572,...,-0.047404,0.071523,0.038319,0.944094,0.592855,0.650027,1.000000,0.931444,0.740871,0.766760
연령대_40_직장_인구_수,0.462491,-0.053048,-0.126328,-0.084780,0.015777,0.083784,0.054718,0.085857,-0.005431,0.064725,...,-0.105548,0.005107,-0.027117,0.847065,0.370363,0.432638,0.931444,1.000000,0.894094,0.734155
연령대_50_직장_인구_수,0.501894,-0.138461,-0.127476,-0.066861,0.101913,0.117377,0.079069,0.146341,0.027565,0.092360,...,-0.107798,-0.019083,-0.032772,0.713371,0.250989,0.301376,0.740871,0.894094,1.000000,0.721891
연령대_60_이상_직장_인구_수,0.563573,-0.100092,-0.162288,0.094978,0.073485,0.147824,0.177186,0.230649,0.247984,0.314965,...,0.126023,0.249459,0.213581,0.749635,0.438526,0.473584,0.766760,0.734155,0.721891,1.000000

In [70]:
corr['총_매출_금액']

총_매출_금액              1.000000
개업_율                -0.127059
폐업_률                -0.028373
아파트_단지_수            -0.154192
아파트_평균_면적            0.547432
아파트_평균_시가            0.508513
운영_영업_개월_평균         -0.022739
폐업_영업_개월_평균          0.119591
총 상주인구 수             0.164938
총 가구 수               0.293168
총_생활인구_수             0.109445
연령대_10_생활인구_수        0.061372
연령대_20_생활인구_수        0.243422
연령대_30_생활인구_수        0.128928
연령대_40_생활인구_수        0.121222
연령대_50_생활인구_수        0.094430
연령대_60_이상_생활인구_수     0.044339
주중_생활인구_수            0.115451
주말_생활인구_수            0.094686
총_직장_인구_수            0.429260
연령대_10_직장_인구_수       0.335366
연령대_20_직장_인구_수       0.429171
연령대_30_직장_인구_수       0.513499
연령대_40_직장_인구_수       0.573052
연령대_50_직장_인구_수       0.445230
연령대_60_이상_직장_인구_수    0.265275
Name: 총_매출_금액, dtype: float64

In [87]:
type(corr['총_매출_금액'])

pandas.core.series.Series

In [101]:
rank = corr['총_매출_금액'][corr['총_매출_금액'].rank()>=15].sort_values(ascending=False)
rank

총_매출_금액              1.000000
연령대_40_직장_인구_수       0.573052
아파트_평균_면적            0.547432
연령대_30_직장_인구_수       0.513499
아파트_평균_시가            0.508513
연령대_50_직장_인구_수       0.445230
총_직장_인구_수            0.429260
연령대_20_직장_인구_수       0.429171
연령대_10_직장_인구_수       0.335366
총 가구 수               0.293168
연령대_60_이상_직장_인구_수    0.265275
연령대_20_생활인구_수        0.243422
Name: 총_매출_금액, dtype: float64

In [43]:
for i in s1df_c:
    print(i)

상권_구분_코드_명
시군구명
총_매출_금액
개업_율
폐업_률
아파트_단지_수
아파트_평균_면적
아파트_평균_시가
상권_변화_지표
상권_변화_지표_명
운영_영업_개월_평균
폐업_영업_개월_평균
총 상주인구 수
총 가구 수
총_생활인구_수
연령대_10_생활인구_수
연령대_20_생활인구_수
연령대_30_생활인구_수
연령대_40_생활인구_수
연령대_50_생활인구_수
연령대_60_이상_생활인구_수
주중_생활인구_수
주말_생활인구_수
총_직장_인구_수
연령대_10_직장_인구_수
연령대_20_직장_인구_수
연령대_30_직장_인구_수
연령대_40_직장_인구_수
연령대_50_직장_인구_수
연령대_60_이상_직장_인구_수

In [44]:
for i,element in enumerate(s1df_c):
    print(i,element)

0 상권_구분_코드_명
1 시군구명
2 총_매출_금액
3 개업_율
4 폐업_률
5 아파트_단지_수
6 아파트_평균_면적
7 아파트_평균_시가
8 상권_변화_지표
9 상권_변화_지표_명
10 운영_영업_개월_평균
11 폐업_영업_개월_평균
12 총 상주인구 수
13 총 가구 수
14 총_생활인구_수
15 연령대_10_생활인구_수
16 연령대_20_생활인구_수
17 연령대_30_생활인구_수
18 연령대_40_생활인구_수
19 연령대_50_생활인구_수
20 연령대_60_이상_생활인구_수
21 주중_생활인구_수
22 주말_생활인구_수
23 총_직장_인구_수
24 연령대_10_직장_인구_수
25 연령대_20_직장_인구_수
26 연령대_30_직장_인구_수
27 연령대_40_직장_인구_수
28 연령대_50_직장_인구_수
29 연령대_60_이상_직장_인구_수

In [58]:
corr = s1df_c[s1df_c['시군구명']==a.unique()[0]].corr(method='pearson')
corr

,총_매출_금액,개업_율,폐업_률,아파트_단지_수,아파트_평균_면적,아파트_평균_시가,운영_영업_개월_평균,폐업_영업_개월_평균,총 상주인구 수,총 가구 수,...,연령대_60_이상_생활인구_수,주중_생활인구_수,주말_생활인구_수,총_직장_인구_수,연령대_10_직장_인구_수,연령대_20_직장_인구_수,연령대_30_직장_인구_수,연령대_40_직장_인구_수,연령대_50_직장_인구_수,연령대_60_이상_직장_인구_수
총_매출_금액,1.000000,-0.078531,-0.129004,-0.229636,0.357993,0.548101,0.348496,0.284756,0.101159,0.163361,...,0.437920,0.520219,0.388993,0.776166,0.165711,0.555876,0.810266,0.830451,0.778668,0.676145
개업_율,-0.078531,1.000000,0.771636,0.144277,-0.065427,-0.079263,0.098022,-0.179809,0.106628,0.113969,...,0.125926,0.075847,0.159125,-0.054751,-0.012839,-0.038900,-0.064471,-0.062411,-0.049713,-0.015733
폐업_률,-0.129004,0.771636,1.000000,0.252949,-0.162777,-0.161928,0.004289,-0.304963,0.104765,0.072271,...,0.106763,0.055486,0.123294,-0.121595,-0.121867,-0.127906,-0.118672,-0.115237,-0.103527,-0.088299
아파트_단지_수,-0.229636,0.144277,0.252949,1.000000,-0.093547,-0.186335,-0.295586,-0.182441,0.706178,0.576359,...,0.091273,0.044398,0.184119,-0.206673,-0.123194,-0.195365,-0.209960,-0.203562,-0.184691,-0.159681
아파트_평균_면적,0.357993,-0.065427,-0.162777,-0.093547,1.000000,0.905897,-0.233029,0.101833,0.016988,-0.136339,...,-0.256889,-0.243550,-0.317713,0.170764,0.036426,0.075624,0.153317,0.196405,0.207138,0.249010
아파트_평균_시가,0.548101,-0.079263,-0.161928,-0.186335,0.905897,1.000000,-0.120369,0.053602,0.033688,-0.094042,...,-0.219747,-0.178990,-0.278651,0.288833,-0.079065,0.078094,0.285688,0.354599,0.353086,0.416655
운영_영업_개월_평균,0.348496,0.098022,0.004289,-0.295586,-0.233029,-0.120369,1.000000,0.435641,0.084728,0.256706,...,0.406293,0.415187,0.328175,0.578677,0.416008,0.577777,0.570460,0.538100,0.532448,0.488885
폐업_영업_개월_평균,0.284756,-0.179809,-0.304963,-0.182441,0.101833,0.053602,0.435641,1.000000,0.089493,0.115617,...,0.292550,0.312125,0.190021,0.515645,0.351779,0.511391,0.514998,0.491259,0.477044,0.371468
총 상주인구 수,0.101159,0.106628,0.104765,0.706178,0.016988,0.033688,0.084728,0.089493,1.000000,0.945294,...,0.377087,0.342524,0.394632,0.300665,0.034470,0.187809,0.281617,0.300704,0.369164,0.402494
총 가구 수,0.163361,0.113969,0.072271,0.576359,-0.136339,-0.094042,0.256706,0.115617,0.945294,1.000000,...,0.552689,0.517710,0.564849,0.386529,0.077536,0.276697,0.376573,0.382294,0.446719,0.425772
총_생활인구_수,0.496840,0.093039,0.069447,0.072761,-0.259881,-0.200075,0.400092,0.289374,0.354992,0.530194,...,0.986934,0.998571,0.976886,0.637335,0.106301,0.508664,0.657597,0.645736,0.675274,0.491974
연령대_10_생활인구_수,0.112606,0.231103,0.241003,0.542984,-0.295047,-0.296733,0.002894,-0.045758,0.507411,0.559758,...,0.606403,0.618756,0.776681,0.139149,-0.056305,0.081793,0.140109,0.135857,0.185293,0.163224
연령대_20_생활인구_수,0.431704,0.016876,-0.026780,0.035172,-0.311397,-0.269407,0.301240,0.199001,0.234929,0.420226,...,0.880733,0.926341,0.944150,0.530759,0.099285,0.438349,0.552753,0.535403,0.550143,0.380120
연령대_30_생활인구_수,0.577166,0.062816,0.037609,-0.010306,-0.214794,-0.125048,0.443843,0.341579,0.323442,0.492935,...,0.971265,0.993227,0.937424,0.717185,0.134842,0.571596,0.739148,0.729816,0.750452,0.565455
연령대_40_생활인구_수,0.557804,0.078705,0.064140,0.045103,-0.214162,-0.131340,0.434430,0.333467,0.360026,0.525173,...,0.982770,0.994309,0.942667,0.698612,0.118738,0.551042,0.721065,0.713041,0.736122,0.546906
연령대_50_생활인구_수,0.489894,0.121574,0.102093,0.061772,-0.238341,-0.182809,0.438028,0.309817,0.364727,0.541108,...,0.995830,0.990099,0.950981,0.642138,0.103006,0.509961,0.663112,0.651770,0.683924,0.488791
연령대_60_이상_생활인구_수,0.437920,0.125926,0.106763,0.091273,-0.256889,-0.219747,0.406293,0.292550,0.377087,0.552689,...,1.000000,0.985891,0.962656,0.604960,0.097651,0.484778,0.620717,0.608165,0.651516,0.468844
주중_생활인구_수,0.520219,0.075847,0.055486,0.044398,-0.243550,-0.178990,0.415187,0.312125,0.342524,0.517710,...,0.985891,1.000000,0.964067,0.664233,0.117078,0.531324,0.685959,0.674021,0.700072,0.509628
주말_생활인구_수,0.388993,0.159125,0.123294,0.184119,-0.317713,-0.278651,0.328175,0.190021,0.394632,0.564849,...,0.962656,0.964067,1.000000,0.511365,0.060124,0.403352,0.525184,0.513971,0.556609,0.407167
총_직장_인구_수,0.776166,-0.054751,-0.121595,-0.206673,0.170764,0.288833,0.578677,0.515645,0.300665,0.386529,...,0.604960,0.664233,0.511365,1.000000,0.518510,0.894429,0.993486,0.978898,0.970180,0.877673
연령대_10_직장_인구_수,0.165711,-0.012839,-0.121867,-0.123194,0.036426,-0.079065,0.416008,0.351779,0.034470,0.077536,...,0.097651,0.117078,0.060124,0.518510,1.000000,0.834443,0.467216,0.348203,0.329441,0.344249
연령대_20_직장_인구_수,0.555876,-0.038900,-0.127906,-0.195365,0.075624,0.078094,0.577777,0.511391,0.187809,0.276697,...,0.484778,0.531324,0.403352,0.894429,0.834443,1.000000,0.867251,0.791735,0.775278,0.703232
연령대_30_직장_인구_수,0.810266,-0.064471,-0.118672,-0.209960,0.153317,0.285688,0.570460,0.514998,0.281617,0.376573,...,0.620717,0.685959,0.525184,0.993486,0.467216,0.867251,1.000000,0.987857,0.963813,0.838802
연령대_40_직장_인구_수,0.830451,-0.062411,-0.115237,-0.203562,0.196405,0.354599,0.538100,0.491259,0.300704,0.382294,...,0.608165,0.674021,0.513971,0.978898,0.348203,0.791735,0.987857,1.000000,0.980278,0.862629
연령대_50_직장_인구_수,0.778668,-0.049713,-0.103527,-0.184691,0.207138,0.353086,0.532448,0.477044,0.369164,0.446719,...,0.651516,0.700072,0.556609,0.970180,0.329441,0.775278,0.963813,0.980278,1.000000,0.923383
연령대_60_이상_직장_인구_수,0.676145,-0.015733,-0.088299,-0.159681,0.249010,0.416655,0.488885,0.371468,0.402494,0.425772,...,0.468844,0.509628,0.407167,0.877673,0.344249,0.703232,0.838802,0.862629,0.923383,1.000000

In [107]:
a = s1df_c['시군구명'] # 항상 같으니깐 빼야함!

for i,element in enumerate(a.unique()):
    print('---------------------------------')
    print(element)
    corr = s1df_c[s1df_c['시군구명']==a.unique()[i]].corr(method='pearson')
    rank = corr['총_매출_금액'][corr['총_매출_금액'].rank()>=16].sort_values(ascending=False) # rank()가 15 이상인 항목을 상관관계 크기 순서대로 
    print(rank)

---------------------------------
종로구
총_매출_금액              1.000000
연령대_40_직장_인구_수       0.830451
연령대_30_직장_인구_수       0.810266
연령대_50_직장_인구_수       0.778668
총_직장_인구_수            0.776166
연령대_60_이상_직장_인구_수    0.676145
연령대_30_생활인구_수        0.577166
연령대_40_생활인구_수        0.557804
연령대_20_직장_인구_수       0.555876
아파트_평균_시가            0.548101
주중_생활인구_수            0.520219
Name: 총_매출_금액, dtype: float64
---------------------------------
중구
총_매출_금액              1.000000
연령대_30_직장_인구_수       0.896057
연령대_20_직장_인구_수       0.894844
총_직장_인구_수            0.881992
연령대_40_직장_인구_수       0.871610
연령대_50_직장_인구_수       0.826988
연령대_10_직장_인구_수       0.808154
연령대_60_이상_직장_인구_수    0.754773
아파트_평균_시가            0.625312
운영_영업_개월_평균          0.298288
아파트_평균_면적            0.291313
Name: 총_매출_금액, dtype: float64
---------------------------------
용산구
총_매출_금액              1.000000
연령대_60_이상_직장_인구_수    0.563573
연령대_30_직장_인구_수       0.512194
연령대_50_직장_인구_수       0.501894
연령대_40_직장_인구_수       0.462491
연령대_20_생활인구_수        0.453924
총_직장_인구_수            0.438037
총 가구 수               0.377632
연령대_30_생활인구_수        0.358537
주말_생활인구_수            0.259599
아파트_평균_면적            0.254122
Name: 총_매출_금액, dtype: float64
---------------------------------
성동구
총_매출_금액              1.000000
연령대_60_이상_직장_인구_수    0.274554
연령대_40_직장_인구_수       0.234568
총_직장_인구_수            0.228292
연령대_30_직장_인구_수       0.216183
연령대_20_직장_인구_수       0.192588
연령대_10_직장_인구_수       0.178414
연령대_50_직장_인구_수       0.157072
연령대_30_생활인구_수        0.117640
연령대_20_생활인구_수        0.117322
아파트_평균_시가            0.099566
Name: 총_매출_금액, dtype: float64
---------------------------------
광진구
총_매출_금액              1.000000
연령대_20_생활인구_수        0.568003
연령대_10_직장_인구_수       0.327150
주말_생활인구_수            0.203504
총_생활인구_수             0.174576
주중_생활인구_수            0.162390
연령대_60_이상_직장_인구_수    0.149031
연령대_30_생활인구_수        0.143099
연령대_20_직장_인구_수       0.135374
총_직장_인구_수            0.102838
연령대_30_직장_인구_수       0.083758
Name: 총_매출_금액, dtype: float64
---------------------------------
동대문구
총_매출_금액              1.000000
연령대_20_생활인구_수        0.186668
연령대_60_이상_직장_인구_수   -0.003407
연령대_20_직장_인구_수      -0.015243
총_직장_인구_수           -0.043350
연령대_50_직장_인구_수      -0.046394
연령대_30_직장_인구_수      -0.054051
연령대_40_직장_인구_수      -0.056768
주중_생활인구_수           -0.056963
총_생활인구_수            -0.064754
연령대_10_직장_인구_수      -0.080652
Name: 총_매출_금액, dtype: float64
---------------------------------
중랑구
총_매출_금액              1.000000
연령대_50_직장_인구_수       0.268164
개업_율                 0.246075
연령대_60_이상_직장_인구_수    0.225935
연령대_10_직장_인구_수       0.221664
총_직장_인구_수            0.204217
연령대_40_직장_인구_수       0.189363
연령대_10_생활인구_수        0.117628
연령대_30_직장_인구_수       0.097749
연령대_20_직장_인구_수       0.083897
운영_영업_개월_평균          0.075098
Name: 총_매출_금액, dtype: float64
---------------------------------
성북구
총_매출_금액           1.000000
연령대_20_생활인구_수     0.711941
연령대_30_생활인구_수     0.411676
주중_생활인구_수         0.349915
총_생활인구_수          0.341060
주말_생활인구_수         0.318658
연령대_40_생활인구_수     0.204805
연령대_10_생활인구_수     0.157222
연령대_10_직장_인구_수    0.117881
연령대_50_생활인구_수     0.110161
연령대_20_직장_인구_수    0.098467
Name: 총_매출_금액, dtype: float64
---------------------------------
강북구
총_매출_금액              1.000000
연령대_60_이상_직장_인구_수    0.740556
총_직장_인구_수            0.738258
연령대_20_직장_인구_수       0.733417
연령대_50_직장_인구_수       0.726364
연령대_40_직장_인구_수       0.679501
연령대_30_직장_인구_수       0.674547
연령대_10_직장_인구_수       0.521091
연령대_20_생활인구_수        0.479425
연령대_30_생활인구_수        0.334417
주중_생활인구_수            0.289167
Name: 총_매출_금액, dtype: float64
---------------------------------
도봉구
총_매출_금액             1.000000
연령대_20_생활인구_수       0.624105
연령대_30_생활인구_수       0.600166
연령대_40_생활인구_수       0.584471
주중_생활인구_수           0.565519
총_생활인구_수            0.560574
연령대_50_생활인구_수       0.550771
주말_생활인구_수           0.547267
연령대_60_이상_생활인구_수    0.530981
연령대_30_직장_인구_수      0.443088
연령대_10_생활인구_수       0.436980
Name: 총_매출_금액, dtype: float64
---------------------------------
노원구
총_매출_금액           1.000000
연령대_20_직장_인구_수    0.575057
연령대_10_직장_인구_수    0.530254
연령대_20_생활인구_수     0.429718
연령대_30_생활인구_수     0.201440
연령대_10_생활인구_수     0.114014
총_직장_인구_수         0.110097
주중_생활인구_수         0.107065
총_생활인구_수          0.098643
주말_생활인구_수         0.078195
연령대_40_생활인구_수     0.071037
Name: 총_매출_금액, dtype: float64
---------------------------------
은평구
총_매출_금액             1.000000
연령대_20_생활인구_수       0.560239
연령대_20_직장_인구_수      0.408900
연령대_50_생활인구_수       0.296549
연령대_10_직장_인구_수      0.280629
주중_생활인구_수           0.277071
총_생활인구_수            0.265087
연령대_30_생활인구_수       0.253825
주말_생활인구_수           0.235504
연령대_60_이상_생활인구_수    0.235308
연령대_30_직장_인구_수      0.225174
Name: 총_매출_금액, dtype: float64
---------------------------------
서대문구
총_매출_금액           1.000000
연령대_20_생활인구_수     0.846663
주말_생활인구_수         0.543211
총_생활인구_수          0.416067
주중_생활인구_수         0.372458
연령대_30_생활인구_수     0.299168
연령대_20_직장_인구_수    0.278953
연령대_10_생활인구_수     0.247063
연령대_10_직장_인구_수    0.188675
연령대_40_직장_인구_수    0.179928
연령대_30_직장_인구_수    0.176892
Name: 총_매출_금액, dtype: float64
---------------------------------
마포구
총_매출_금액           1.000000
연령대_20_생활인구_수     0.941105
연령대_30_생활인구_수     0.883052
주말_생활인구_수         0.877141
총_생활인구_수          0.864983
주중_생활인구_수         0.857900
연령대_10_생활인구_수     0.765323
연령대_40_생활인구_수     0.746450
연령대_50_생활인구_수     0.645857
연령대_10_직장_인구_수    0.640802
연령대_30_직장_인구_수    0.590862
Name: 총_매출_금액, dtype: float64
---------------------------------
양천구
총_매출_금액           1.000000
연령대_10_생활인구_수     0.348972
연령대_40_생활인구_수     0.305620
연령대_30_직장_인구_수    0.303177
주중_생활인구_수         0.236813
연령대_20_직장_인구_수    0.233188
총_생활인구_수          0.225402
연령대_20_생활인구_수     0.215523
연령대_50_생활인구_수     0.203444
주말_생활인구_수         0.196612
연령대_30_생활인구_수     0.187293
Name: 총_매출_금액, dtype: float64
---------------------------------
강서구
총_매출_금액              1.000000
총_직장_인구_수            0.331985
연령대_30_직장_인구_수       0.323521
연령대_50_직장_인구_수       0.315868
연령대_40_직장_인구_수       0.312223
연령대_20_직장_인구_수       0.308304
연령대_60_이상_직장_인구_수    0.246086
연령대_10_직장_인구_수       0.177242
아파트_평균_시가            0.168600
폐업_영업_개월_평균          0.165320
아파트_평균_면적            0.041974
Name: 총_매출_금액, dtype: float64
---------------------------------
구로구
총_매출_금액              1.000000
연령대_30_직장_인구_수       0.936811
연령대_40_직장_인구_수       0.936315
총_직장_인구_수            0.934509
연령대_20_직장_인구_수       0.932934
연령대_50_직장_인구_수       0.917120
연령대_10_직장_인구_수       0.915569
연령대_60_이상_직장_인구_수    0.888340
연령대_20_생활인구_수        0.389478
연령대_30_생활인구_수        0.385223
연령대_40_생활인구_수        0.196988
Name: 총_매출_금액, dtype: float64
---------------------------------
금천구
총_매출_금액              1.000000
연령대_10_직장_인구_수       0.883959
연령대_50_직장_인구_수       0.883243
연령대_20_직장_인구_수       0.877798
연령대_40_직장_인구_수       0.860490
총_직장_인구_수            0.850624
연령대_30_직장_인구_수       0.847398
연령대_60_이상_직장_인구_수    0.451882
연령대_20_생활인구_수        0.173950
연령대_30_생활인구_수        0.142971
연령대_40_생활인구_수        0.108456
Name: 총_매출_금액, dtype: float64
---------------------------------
영등포구
총_매출_금액              1.000000
연령대_30_직장_인구_수       0.573509
총_직장_인구_수            0.552104
연령대_20_직장_인구_수       0.549867
연령대_40_직장_인구_수       0.544409
연령대_50_직장_인구_수       0.504151
연령대_10_직장_인구_수       0.493012
연령대_60_이상_직장_인구_수    0.465212
아파트_평균_시가            0.446740
아파트_평균_면적            0.360671
연령대_30_생활인구_수        0.277070
Name: 총_매출_금액, dtype: float64
---------------------------------
동작구
총_매출_금액             1.000000
연령대_20_생활인구_수       0.297672
연령대_30_생활인구_수       0.244074
주중_생활인구_수           0.230280
연령대_40_생활인구_수       0.200747
총_생활인구_수            0.197826
연령대_50_생활인구_수       0.165175
연령대_60_이상_생활인구_수    0.117697
주말_생활인구_수           0.117402
연령대_40_직장_인구_수      0.117029
연령대_30_직장_인구_수      0.090230
Name: 총_매출_금액, dtype: float64
---------------------------------
관악구
총_매출_금액              1.000000
연령대_60_이상_직장_인구_수    0.691811
연령대_10_직장_인구_수       0.498398
연령대_20_생활인구_수        0.452604
연령대_30_생활인구_수        0.347056
주중_생활인구_수            0.338691
총_생활인구_수             0.330372
연령대_50_직장_인구_수       0.323389
주말_생활인구_수            0.308425
총_직장_인구_수            0.281952
연령대_40_생활인구_수        0.248838
Name: 총_매출_금액, dtype: float64
---------------------------------
서초구
총_매출_금액           1.000000
연령대_20_생활인구_수     0.779976
연령대_30_직장_인구_수    0.720076
연령대_20_직장_인구_수    0.713628
연령대_30_생활인구_수     0.695710
주중_생활인구_수         0.660562
연령대_40_직장_인구_수    0.650665
연령대_10_직장_인구_수    0.649868
총_직장_인구_수         0.640737
연령대_40_생활인구_수     0.621598
총_생활인구_수          0.620003
Name: 총_매출_금액, dtype: float64
---------------------------------
강남구
총_매출_금액           1.000000
연령대_20_생활인구_수     0.843820
연령대_30_생활인구_수     0.806581
주중_생활인구_수         0.781194
총_직장_인구_수         0.766198
총_생활인구_수          0.763668
연령대_40_직장_인구_수    0.761938
연령대_40_생활인구_수     0.736762
연령대_20_직장_인구_수    0.736656
연령대_30_직장_인구_수    0.730923
연령대_50_생활인구_수     0.723564
Name: 총_매출_금액, dtype: float64
---------------------------------
송파구
총_매출_금액              1.000000
연령대_10_직장_인구_수       0.960183
연령대_20_직장_인구_수       0.897466
연령대_30_직장_인구_수       0.868877
총_직장_인구_수            0.864631
연령대_40_직장_인구_수       0.820065
연령대_50_직장_인구_수       0.795241
아파트_평균_시가            0.786291
연령대_60_이상_직장_인구_수    0.764887
아파트_평균_면적            0.710075
연령대_20_생활인구_수        0.631274
Name: 총_매출_금액, dtype: float64
---------------------------------
강동구
총_매출_금액              1.000000
연령대_40_직장_인구_수       0.573052
아파트_평균_면적            0.547432
연령대_30_직장_인구_수       0.513499
아파트_평균_시가            0.508513
연령대_50_직장_인구_수       0.445230
총_직장_인구_수            0.429260
연령대_20_직장_인구_수       0.429171
연령대_10_직장_인구_수       0.335366
총 가구 수               0.293168
연령대_60_이상_직장_인구_수    0.265275
Name: 총_매출_금액, dtype: float64

In [61]:
# 구별로 묶기
# 합계 열 grouping
s1df_sum_group = s1df.groupby(['시군구명'])['점포수','프랜차이즈_점포_수','폐업_점포_수', '총_매출_금액', '주중_매출_금액',
                      '주말_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
                      '시간대_14~17_매출_금액', '시간대_17~21_매출_금액','연령대_10_매출_금액',
                      '연령대_20_매출_금액', '연령대_30_매출_금액', '연령대_40_매출_금액',
                      '연령대_50_매출_금액', '연령대_60_이상_매출_금액','아파트_단지_수',
                      '총 상주인구 수', '총 가구 수', '총_생활인구_수', '연령대_10_생활인구_수',
                      '연령대_20_생활인구_수', '연령대_30_생활인구_수', '연령대_40_생활인구_수',
                      '연령대_50_생활인구_수', '연령대_60_이상_생활인구_수', '주중_생활인구_수',
                      '주말_생활인구_수', '총_직장_인구_수', '연령대_10_직장_인구_수',
                      '연령대_20_직장_인구_수', '연령대_30_직장_인구_수', '연령대_40_직장_인구_수',
                      '연령대_50_직장_인구_수', '연령대_60_이상_직장_인구_수'].sum()

<ipython-input-61-d2d819d8f488>:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  s1df_sum_group = s1df.groupby(['시군구명'])['점포수','프랜차이즈_점포_수','폐업_점포_수', '총_매출_금액', '주중_매출_금액',

In [62]:
s1df_sum_group

,점포수,프랜차이즈_점포_수,폐업_점포_수,총_매출_금액,주중_매출_금액,주말_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,...,연령대_60_이상_생활인구_수,주중_생활인구_수,주말_생활인구_수,총_직장_인구_수,연령대_10_직장_인구_수,연령대_20_직장_인구_수,연령대_30_직장_인구_수,연령대_40_직장_인구_수,연령대_50_직장_인구_수,연령대_60_이상_직장_인구_수
시군구명,,,,,,,,,,,,,,,,,,,,,
강남구,6940.0,531.00,75.50,3.305051e+11,2.635093e+11,6.699576e+10,4.800715e+10,1.113435e+11,7.263387e+10,6.815652e+10,...,10667444.50,56987054.25,17648563.25,505941.0,1774.0,106365.0,155148.0,126091.0,78762.0,37801.0
강동구,1699.0,101.25,17.75,3.410887e+10,2.365264e+10,1.045623e+10,3.953757e+09,9.283571e+09,8.703949e+09,8.479609e+09,...,12092763.00,34827455.25,14310148.75,28429.0,92.0,3313.0,5140.0,6025.0,6623.0,7236.0
강북구,760.0,40.00,7.50,2.221131e+10,1.535105e+10,6.860258e+09,1.551544e+09,5.085926e+09,5.752623e+09,6.866199e+09,...,6432850.50,16678829.00,6810104.75,8162.0,20.0,899.0,1565.0,1947.0,2141.0,1590.0
강서구,1003.0,63.75,11.75,2.042532e+10,1.439581e+10,6.029513e+09,2.103222e+09,5.996192e+09,5.252915e+09,5.177290e+09,...,8387637.00,26890657.00,11039852.75,23001.0,59.0,3084.0,5224.0,5558.0,5378.0,3698.0
관악구,1770.0,121.25,24.75,5.756681e+10,3.797413e+10,1.959268e+10,5.405576e+09,1.190411e+10,1.456478e+10,1.777908e+10,...,8631860.25,32299507.50,13591803.25,21832.0,48.0,3289.0,5491.0,5665.0,4506.0,2833.0
광진구,1520.0,90.75,16.00,4.015802e+10,2.671643e+10,1.344159e+10,2.670263e+09,8.975301e+09,1.061148e+10,1.252213e+10,...,6900757.00,24631585.75,10227786.75,16936.0,43.0,2735.0,3517.0,4299.0,3756.0,2586.0
구로구,1315.0,131.75,11.50,4.117623e+10,3.345532e+10,7.720902e+09,7.443176e+09,1.406171e+10,8.866619e+09,7.828583e+09,...,5503772.25,16572154.75,6630003.75,70502.0,268.0,13509.0,21554.0,17187.0,10857.0,7127.0
금천구,1130.0,118.00,10.75,3.837007e+10,3.369290e+10,4.677175e+09,9.974641e+09,1.506679e+10,7.627875e+09,4.920573e+09,...,2728395.25,8464198.50,3359169.25,63051.0,208.0,11409.0,17438.0,14331.0,9392.0,10273.0
노원구,564.0,43.50,3.25,2.864346e+10,1.955682e+10,9.086644e+09,3.433279e+09,6.455942e+09,7.829200e+09,7.959453e+09,...,3687134.25,9921074.25,4235412.25,4529.0,13.0,493.0,710.0,1083.0,1197.0,1033.0
도봉구,616.0,41.75,5.75,1.402271e+10,9.415862e+09,4.606848e+09,1.239459e+09,3.857482e+09,4.062383e+09,3.999999e+09,...,4657385.75,11171617.50,4668712.25,6387.0,8.0,707.0,1077.0,1558.0,1800.0,1237.0
동대문구,1302.0,84.00,12.25,3.505083e+10,2.593473e+10,9.116098e+09,3.686859e+09,1.076148e+10,8.778322e+09,9.236671e+09,...,8001532.00,23159235.50,9232519.00,31622.0,86.0,3973.0,6749.0,8124.0,7632.0,5058.0
동작구,1578.0,110.25,17.00,5.177588e+10,3.651974e+10,1.525614e+10,6.753724e+09,1.572319e+10,1.279083e+10,1.319896e+10,...,7057705.25,22427465.75,9193789.75,31179.0,88.0,5381.0,6623.0,6219.0,7001.0,5867.0
마포구,4158.0,145.25,51.50,1.650636e+11,1.124226e+11,5.264099e+10,1.077743e+10,3.921406e+10,4.675678e+10,5.030355e+10,...,6335367.75,27923960.50,10871508.50,62913.0,322.0,12938.0,16240.0,14112.0,11485.0,7816.0
서대문구,1288.0,100.25,13.50,3.663644e+10,2.791111e+10,8.725333e+09,4.144473e+09,1.050502e+10,9.265452e+09,9.854452e+09,...,4059628.00,15639666.75,5605374.25,16800.0,50.0,2219.0,4208.0,4164.0,4530.0,1629.0
서초구,3561.0,255.25,32.50,1.530912e+11,1.238377e+11,2.925348e+10,2.397864e+10,5.502850e+10,3.348937e+10,2.915956e+10,...,7576083.25,31750716.00,10393044.75,208578.0,638.0,42144.0,58305.0,50551.0,37553.0,19387.0
성동구,1253.0,65.00,13.75,3.558044e+10,2.604389e+10,9.536548e+09,4.283717e+09,1.164410e+10,9.885621e+09,8.469227e+09,...,4493616.75,16360382.75,6111039.75,35293.0,146.0,5935.0,8261.0,7962.0,7756.0,5233.0
성북구,1274.0,81.75,11.75,4.421920e+10,3.073440e+10,1.348479e+10,2.855666e+09,1.121798e+10,1.183162e+10,1.392079e+10,...,6500655.50,20831741.25,8492787.50,39500.0,127.0,3657.0,9940.0,11768.0,9990.0,4018.0
송파구,2056.0,153.00,20.25,9.610305e+10,7.078712e+10,2.531593e+10,1.214189e+10,2.747038e+10,2.311245e+10,2.346048e+10,...,7966208.00,28595208.25,11263163.25,122412.0,343.0,18987.0,30372.0,30688.0,26834.0,15188.0
양천구,823.0,49.00,8.50,1.061635e+10,7.581000e+09,3.035347e+09,1.010373e+09,3.402362e+09,2.878986e+09,2.583753e+09,...,5493418.50,16754099.00,6910783.25,12863.0,50.0,1295.0,2485.0,2894.0,3091.0,3048.0
영등포구,1780.0,145.25,18.25,7.268561e+10,5.682315e+10,1.586246e+10,1.065536e+10,2.237844e+10,1.529006e+10,1.656895e+10,...,5974948.50,19962914.75,7735261.25,74390.0,257.0,11737.0,20012.0,19954.0,14456.0,7974.0
용산구,2335.0,110.50,26.25,7.748346e+10,5.411033e+10,2.337313e+10,6.529287e+09,2.305405e+10,2.198284e+10,2.084363e+10,...,4709018.25,16895708.50,6561525.25,60798.0,396.0,16230.0,17778.0,13907.0,8803.0,3684.0
은평구,883.0,44.75,12.25,1.578472e+10,1.061241e+10,5.172305e+09,1.055799e+09,3.364622e+09,4.278960e+09,5.087678e+09,...,7821160.75,21965838.75,9159244.50,12044.0,21.0,1414.0,2177.0,2747.0,2883.0,2802.0
종로구,3655.0,246.50,23.00,1.291803e+11,9.892203e+10,3.025826e+10,1.545299e+10,4.533540e+10,3.320610e+10,2.826526e+10,...,3760668.00,13892962.50,4348594.75,162620.0,1896.0,29884.0,47413.0,45453.0,27862.0,10112.0
중구,2052.0,145.00,16.75,8.998935e+10,7.755066e+10,1.243869e+10,1.853204e+10,3.300875e+10,1.731515e+10,1.367599e+10,...,4641777.00,16555445.50,5160928.75,93684.0,335.0,16393.0,27738.0,25774.0,16428.0,7016.0
중랑구,743.0,39.50,8.25,1.202530e+10,8.140844e+09,3.884452e+09,1.180844e+09,2.937681e+09,3.110575e+09,3.284947e+09,...,7658541.50,20918516.25,8708006.25,8650.0,14.0,1081.0,1656.0,2058.0,2350.0,1491.0

In [63]:
# 평균 열 grouping
s1df_mean_group = s1df.groupby(['시군구명'])['개업_율', '폐업_률', '아파트_평균_면적',
                                        '아파트_평균_시가', '운영_영업_개월_평균',
                                        '폐업_영업_개월_평균'].mean()

<ipython-input-63-d5e6856df98e>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  s1df_mean_group = s1df.groupby(['시군구명'])['개업_율', '폐업_률', '아파트_평균_면적',

In [64]:
s1df_mean_group

          개업_율      폐업_률  아파트_평균_면적     아파트_평균_시가  운영_영업_개월_평균  폐업_영업_개월_평균
시군구명
강남구   5.544271  4.562500  64.843750  4.122218e+08   104.114583    49.906250
강동구   6.367925  4.268868  53.075472  1.926590e+08   109.905660    50.320755
강북구   5.712121  3.613636  50.363636  1.327919e+08   107.939394    50.303030
강서구   6.901961  5.901961  52.000000  1.574343e+08   106.745098    51.313725
관악구   6.133621  5.788793  50.758621  1.628367e+08   108.931034    53.189655
광진구   6.852273  5.198864  52.772727  2.028018e+08   108.477273    52.727273
구로구   5.315476  5.023810  52.761905  1.528953e+08   112.619048    52.571429
금천구   7.425926  4.111111  50.296296  1.414185e+08   113.037037    52.925926
노원구   3.571429  2.357143  50.142857  1.349492e+08   104.357143    50.214286
도봉구   5.527778  2.777778  48.740741  1.117613e+08   106.222222    50.148148
동대문구  6.485000  5.050000  52.080000  1.690880e+08   119.960000    55.640000
동작구   6.104167  5.557292  55.916667  2.170744e+08   114.520833    54.270833
마포구   5.572727  5.409091  56.872727  2.496234e+08    98.981818    52.418182
서대문구  5.312500  4.125000  52.650000  1.685708e+08   118.350000    58.650000
서초구   5.991667  3.483333  65.466667  3.468079e+08   116.550000    52.483333
성동구   6.615385  4.339744  51.923077  2.269039e+08   106.615385    57.230769
성북구   5.261111  4.200000  52.022222  1.441392e+08   112.200000    56.088889
송파구   5.797297  5.418919  55.459459  2.427221e+08   107.378378    50.081081
양천구   6.447674  4.453488  52.790698  1.598069e+08   111.023256    51.023256
영등포구  6.677778  5.783333  52.222222  2.040449e+08   117.022222    53.800000
용산구   5.397959  4.872449  63.551020  3.678388e+08   118.489796    58.000000
은평구   7.668605  5.959302  52.279070  1.485709e+08   114.139535    54.465116
종로구   3.700000  3.457143  66.085714  2.273844e+08   114.228571    57.914286
중구    5.393939  2.840909  57.363636  2.077901e+08   132.666667    63.424242
중랑구   5.448718  5.628205  50.923077  1.462630e+08   109.384615    51.769231

In [65]:
print(s1df_mean_group.shape,s1df_sum_group.shape)

(25, 6) (25, 35)

In [13]:
s2df = pd.concat([s1df_sum_group,s1df_mean_group], axis=1)

In [14]:
# 총매출 제외 매출 칼럼 제거
s3df = s2df.drop(['주중_매출_금액', '주말_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
          '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '연령대_10_매출_금액',
          '연령대_20_매출_금액', '연령대_30_매출_금액', '연령대_40_매출_금액',
          '연령대_50_매출_금액', '연령대_60_이상_매출_금액'], axis=1)

In [15]:
# 상관관계 분석
corr = s3df.corr(method='pearson')

In [16]:
s3df.iloc[2].corr(method='pearson')

TypeError: corr() missing 1 required positional argument: 'other'

In [17]:
corr.iloc[3][corr.iloc[3]>0.5]

점포수                  0.981904
프랜차이즈_점포_수           0.964942
폐업_점포_수              0.950983
총_매출_금액              1.000000
총_생활인구_수             0.523625
연령대_20_생활인구_수        0.553799
연령대_30_생활인구_수        0.708961
연령대_40_생활인구_수        0.683687
주중_생활인구_수            0.583187
총_직장_인구_수            0.934587
연령대_10_직장_인구_수       0.882849
연령대_20_직장_인구_수       0.934138
연령대_30_직장_인구_수       0.931444
연령대_40_직장_인구_수       0.932311
연령대_50_직장_인구_수       0.932687
연령대_60_이상_직장_인구_수    0.895828
아파트_평균_면적            0.601386
아파트_평균_시가            0.753932
Name: 총_매출_금액, dtype: float64

In [18]:
corr

,점포수,프랜차이즈_점포_수,폐업_점포_수,총_매출_금액,아파트_단지_수,총 상주인구 수,총 가구 수,총_생활인구_수,연령대_10_생활인구_수,연령대_20_생활인구_수,...,연령대_30_직장_인구_수,연령대_40_직장_인구_수,연령대_50_직장_인구_수,연령대_60_이상_직장_인구_수,개업_율,폐업_률,아파트_평균_면적,아파트_평균_시가,운영_영업_개월_평균,폐업_영업_개월_평균
점포수,1.000000,0.956655,0.966139,0.981904,0.191778,0.117432,0.173714,0.546757,0.268297,0.573618,...,0.906017,0.906987,0.905183,0.864101,-0.017441,0.202317,0.610523,0.753206,-0.051645,-0.044864
프랜차이즈_점포_수,0.956655,1.000000,0.888553,0.964942,0.154318,0.106822,0.163192,0.514112,0.227323,0.513194,...,0.963562,0.959511,0.956654,0.915396,0.015899,0.157523,0.567831,0.678674,0.028753,-0.008291
폐업_점포_수,0.966139,0.888553,1.000000,0.950983,0.303992,0.249742,0.308167,0.648605,0.390943,0.692857,...,0.850500,0.849204,0.850794,0.832621,0.019016,0.295569,0.553640,0.775405,-0.158226,-0.134961
총_매출_금액,0.981904,0.964942,0.950983,1.000000,0.173494,0.089698,0.151527,0.523625,0.244145,0.553799,...,0.931444,0.932311,0.932687,0.895828,-0.052852,0.161471,0.601386,0.753932,-0.045796,-0.042618
아파트_단지_수,0.191778,0.154318,0.303992,0.173494,1.000000,0.805158,0.709194,0.693271,0.819567,0.493455,...,0.187026,0.201755,0.237542,0.313409,0.296144,0.636992,0.016768,0.263836,-0.517391,-0.583395
총 상주인구 수,0.117432,0.106822,0.249742,0.089698,0.805158,1.000000,0.975420,0.853204,0.890774,0.712481,...,0.114001,0.127338,0.157791,0.237129,0.446902,0.782101,-0.206699,0.155801,-0.499063,-0.594266
총 가구 수,0.173714,0.163192,0.308167,0.151527,0.709194,0.975420,1.000000,0.864634,0.820398,0.799400,...,0.155762,0.168698,0.194620,0.262043,0.405783,0.761916,-0.178442,0.188674,-0.445607,-0.517640
총_생활인구_수,0.546757,0.514112,0.648605,0.523625,0.693271,0.853204,0.864634,1.000000,0.902346,0.909511,...,0.501544,0.513753,0.538840,0.568521,0.352513,0.685613,0.057917,0.429908,-0.422442,-0.464406
연령대_10_생활인구_수,0.268297,0.227323,0.390943,0.244145,0.819567,0.890774,0.820398,0.902346,1.000000,0.710069,...,0.259633,0.276685,0.311964,0.374482,0.376844,0.690528,-0.087907,0.265835,-0.529613,-0.592676
연령대_20_생활인구_수,0.573618,0.513194,0.692857,0.553799,0.493455,0.712481,0.799400,0.909511,0.710069,1.000000,...,0.473296,0.483420,0.500430,0.505330,0.233759,0.565579,0.096207,0.443667,-0.318129,-0.287366
연령대_30_생활인구_수,0.715070,0.689788,0.806313,0.708961,0.634167,0.735820,0.772852,0.953786,0.786828,0.915273,...,0.684835,0.691760,0.712246,0.732999,0.230406,0.585575,0.259917,0.609784,-0.342911,-0.367132
연령대_40_생활인구_수,0.697716,0.677505,0.773070,0.683687,0.671671,0.747577,0.750267,0.967887,0.848218,0.857923,...,0.681946,0.690848,0.712720,0.735305,0.291792,0.603322,0.234333,0.575379,-0.374054,-0.423121
연령대_50_생활인구_수,0.484183,0.475189,0.548818,0.454805,0.665763,0.844539,0.831547,0.961376,0.888398,0.791601,...,0.448791,0.462262,0.486734,0.515866,0.445828,0.716801,-0.033870,0.324158,-0.413679,-0.492907
연령대_60_이상_생활인구_수,0.200609,0.184332,0.286734,0.159018,0.659891,0.887928,0.861085,0.883294,0.885334,0.701401,...,0.159303,0.173920,0.199523,0.239244,0.471837,0.720046,-0.247277,0.080339,-0.438452,-0.523194
주중_생활인구_수,0.604303,0.577071,0.695478,0.583187,0.673320,0.818010,0.831697,0.996708,0.882172,0.908291,...,0.566985,0.578175,0.602068,0.626389,0.336030,0.656989,0.113329,0.476727,-0.399037,-0.440491
주말_생활인구_수,0.370951,0.324619,0.498525,0.343093,0.724330,0.920510,0.925383,0.975137,0.926935,0.882050,...,0.305690,0.320273,0.347772,0.391098,0.385628,0.740636,-0.095504,0.287382,-0.472111,-0.514048
총_직장_인구_수,0.909054,0.963784,0.854898,0.934587,0.205674,0.129920,0.169746,0.515237,0.277697,0.482957,...,0.999182,0.998614,0.996228,0.967663,-0.039389,0.114451,0.603856,0.709980,-0.017442,-0.062553
연령대_10_직장_인구_수,0.902281,0.917066,0.794102,0.882849,0.058389,-0.024696,0.027371,0.371243,0.108381,0.372258,...,0.918979,0.928073,0.912695,0.843133,-0.130971,0.049718,0.643466,0.626038,0.072681,0.062734
연령대_20_직장_인구_수,0.911390,0.967778,0.858740,0.934138,0.176081,0.100051,0.141172,0.491961,0.244268,0.466336,...,0.995554,0.987699,0.981831,0.945740,-0.045010,0.083870,0.607125,0.710829,0.008415,-0.039242
연령대_30_직장_인구_수,0.906017,0.963562,0.850500,0.931444,0.187026,0.114001,0.155762,0.501544,0.259633,0.473296,...,1.000000,0.997612,0.992419,0.958615,-0.048432,0.097694,0.602194,0.698998,-0.007140,-0.052614
연령대_40_직장_인구_수,0.906987,0.959511,0.849204,0.932311,0.201755,0.127338,0.168698,0.513753,0.276685,0.483420,...,0.997612,1.000000,0.997070,0.965080,-0.050115,0.114921,0.604876,0.702285,-0.018498,-0.059780
연령대_50_직장_인구_수,0.905183,0.956654,0.850794,0.932687,0.237542,0.157791,0.194620,0.538840,0.311964,0.500430,...,0.992419,0.997070,1.000000,0.976412,-0.029091,0.143118,0.601706,0.717387,-0.034889,-0.073616
연령대_60_이상_직장_인구_수,0.864101,0.915396,0.832621,0.895828,0.313409,0.237129,0.262043,0.568521,0.374482,0.505330,...,0.958615,0.965080,0.976412,1.000000,0.041869,0.209968,0.554525,0.718699,-0.102916,-0.166423
개업_율,-0.017441,0.015899,0.019016,-0.052852,0.296144,0.446902,0.405783,0.352513,0.376844,0.233759,...,-0.048432,-0.050115,-0.029091,0.041869,1.000000,0.527109,-0.525743,-0.102561,-0.417149,-0.403847
폐업_률,0.202317,0.157523,0.295569,0.161471,0.636992,0.782101,0.761916,0.685613,0.690528,0.565579,...,0.097694,0.114921,0.143118,0.209968,0.527109,1.000000,-0.215532,0.207353,-0.490919,-0.478314
아파트_평균_면적,0.610523,0.567831,0.553640,0.601386,0.016768,-0.206699,-0.178442,0.057917,-0.087907,0.096207,...,0.602194,0.604876,0.601706,0.554525,-0.525743,-0.215532,1.000000,0.774059,0.426608,0.395387
아파트_평균_시가,0.753206,0.678674,0.775405,0.753932,0.263836,0.155801,0.188674,0.429908,0.265835,0.443667,...,0.698998,0.702285,0.717387,0.718699,-0.102561,0.207353,0.774059,1.000000,-0.029291,0.007248
운영_영업_개월_평균,-0.051645,0.028753,-0.158226,-0.045796,-0.517391,-0.499063,-0.445607,-0.422442,-0.529613,-0.318129,...,-0.007140,-0.018498,-0.034889,-0.102916,-0.417149,-0.490919,0.426608,-0.029291,1.000000,0.904703
폐업_영업_개월_평균,-0.044864,-0.008291,-0.134961,-0.042618,-0.583395,-0.594266,-0.517640,-0.464406,-0.592676,-0.287366,...,-0.052614,-0.059780,-0.073616,-0.166423,-0.403847,-0.478314,0.395387,0.007248,0.904703,1.000000